// Knowledge base del agente supplier-finder.
// Canales de sourcing, costo puesto en Colombia y señales de alarma con un proveedor.
// Fuentes: DIAN (tráfico postal y envíos urgentes, consultado sep 2026), Decreto Legislativo 1474 de 2025
// y Concepto DIAN 000407 de ene 2026, Decreto 2598 de 2022, epayco.com/tarifas y soporte.wompi.co (ene 2026), alibaba.com.

export const SOURCING_CHANNELS = `CANALES DE SOURCING (cómo opera cada uno y para qué volumen sirve):

DROPI (dropi.co)
- Dropshipping nacional: el producto ya está en bodega del proveedor dentro del país, vos vendés y ellos despachan. Trabaja con pago contraentrega y opera en Colombia, México, Ecuador, Perú, Chile, Argentina, Panamá y otros mercados de la región.
- El registro no tiene una cuota de suscripción publicada. Lo que NO está publicado en una tabla oficial citable: el porcentaje de comisión, quién asume el flete cuando el cliente rechaza el paquete, y cada cuánto liquidan. Dónde mirarlo, y es el único dato confiable porque es tuyo: panel de Dropi, sección Billetera. Abrí el detalle de un pedido devuelto para ver exactamente qué te descontaron, y el historial de retiros para ver la frecuencia real de liquidación.
- Cuándo conviene: querés validar un producto sin comprar inventario y vender contraentrega esta semana. Volumen de 1 a 200 unidades por mes.

ALIEXPRESS: B2C, sin MOQ, pago internacional directo con tarjeta o PayPal, sitio en español. Precio unitario alto. Sirve para pedir 1 a 10 unidades de muestra y validar demanda. No sirve para escalar: el margen no aguanta la publicidad.
CJ DROPSHIPPING: intermediario con bodegas propias en varios países, hace fulfillment y etiquetado. Plazos típicos de 7 a 20 días según bodega y destino; desde China a Colombia sin bodega regional puede irse a 15 a 45 días. Sirve entre 50 y 500 unidades por mes cuando no querés manejar inventario.
ALIBABA: B2B, MOQ típico desde 50 unidades, sitio en inglés, pago internacional directo dentro de la plataforma con Trade Assurance, que media reclamos cuando el pedido no coincide con lo pactado en calidad, cantidad o plazo, y que se abre dentro de los 30 días de la entrega (alibaba.com, página oficial de Trade Assurance). Sirve de 200 unidades en adelante y cuando querés personalizar producto o empaque.
1688: mercado doméstico chino del mismo grupo, con precios bastante más bajos que Alibaba y AliExpress, pero el sitio está en chino y el pago se hace con Alipay o transferencia bancaria china. En la práctica necesitás un agente de compras o una consolidadora.
- Agente de compras para 1688: consolida varios proveedores, inspecciona, reempaca y despacha. Las comisiones que reportan las agencias van del 3% al 10% del valor del pedido y bajan a mayor volumen, pero no hay tarifa pública estandarizada. Pedí cotización escrita con cinco renglones separados: comisión, inspección, reempaque, flete doméstico en China y flete internacional. Si te dan un solo número, pedí el desglose antes de pagar.
PROVEEDOR LOCAL O MAYORISTA (San Victorino en Bogotá, el cluster textil de Medellín para fajas): gana sobre importar cuando el producto es textil o depende de talla (las devoluciones por talla equivocada se comen el margen), cuando necesitás reponer en días y no en semanas, o cuando el arancel textil hace inviable importar. Compará siempre contra el costo puesto, nunca contra el precio FOB del chino.`

export const LANDED_COST_COLOMBIA = `COSTO PUESTO EN COLOMBIA: FÓRMULA Y UMBRALES:
- Fórmula puerta a puerta, por unidad: costo del producto + flete internacional prorrateado + arancel + IVA + comisión de pasarela + flete nacional + costo esperado de devoluciones. Ese número es el costo puesto. Todo margen se calcula sobre él, nunca sobre el precio FOB.
- Arancel en tráfico postal y envíos urgentes: la DIAN establece que cuando el valor FOB del envío es igual o inferior a USD 200 no se paga gravamen arancelario (dian.gov.co, Modalidad de tráfico postal y envíos urgentes, consultado sep 2026).
- IVA en 2026, el cambio que rompe los cálculos viejos: el umbral de exclusión de IVA bajó de USD 200 a USD 50. Lo fijó el Decreto Legislativo 1474 de 2025 para todo el año 2026 y la DIAN lo confirmó en el Concepto 000407 de enero de 2026. Traducción: entre USD 50 y USD 200 no pagás arancel pero SÍ pagás IVA del 19%. Muchas guías todavía repiten el umbral único de USD 200 para ambos: está desactualizado.
- Por encima de USD 200: régimen ordinario de importación, con arancel según la subpartida arancelaria del producto más IVA del 19%. Buscá la subpartida antes de cotizar, porque el arancel cambia mucho por categoría.
- Textiles y confecciones (capítulos 61 y 62): arancel del 40% para origen sin TLC vigente, según el Decreto 2598 de diciembre de 2022, todavía vigente. Esto es lo que suele hacer inviable importar fajas y ropa frente a comprar nacional.
- Excepción del TLC con Estados Unidos: envíos de hasta USD 200 desde EE.UU. sin fines comerciales quedan exentos de IVA. El requisito de "sin fines comerciales" es justamente el que te deja afuera si importás para revender.
- Pasarelas de pago, tarifas publicadas: ePayco cobra 2,64% + $690 COP + IVA con cuenta Davivienda y 3,29% + $700 COP + IVA con otras cuentas, más $6.500 + IVA por retiro (epayco.com/tarifas, consultado sep 2026). Wompi publica 2,65% + $700 COP + IVA en tarjeta de crédito, plan Avanzado (soporte.wompi.co, artículo actualizado enero 2026). PayU y Mercado Pago no publican tarifa accesible sin cuenta: entrá a tu panel, sección Tarifas o Costos, y copiá el porcentaje y el fijo exactos antes de calcular nada.
- Devoluciones en contraentrega: NO existe una tasa oficial publicada por Dropi ni por Servientrega, Interrapidísimo, Coordinadora o TCC. Todo porcentaje que circula viene de blogs. Medí la tuya: tomá tus últimos 30 pedidos contraentrega, contá cuántos fueron rechazados o no entregados y dividí. Ese porcentaje entra en la fórmula como costo, porque el flete de ida ya se generó aunque nunca cobres el pedido.
- Precio mínimo viable: precio de venta = costo puesto dividido por el resultado de restar a 1 el margen objetivo, la tasa de devolución y el costo de adquisición expresado como fracción del precio. En la práctica, con contraentrega y publicidad paga, el sector trabaja con un precio de venta cercano a 3 veces el costo puesto. Aclaración: la regla del 3x es folclore del sector, no tiene fuente institucional. Usala como punto de partida y reemplazala por tu propio cálculo apenas tengas 30 pedidos reales.`

export const SOURCING_RED_FLAGS = `RED FLAGS DE PROVEEDOR Y DÓNDE SE MIRAN:
1. MOQ oculto detrás del precio unitario. Dónde: la tabla de precio escalonado en la ficha de Alibaba, no el "precio desde" del listado. Si el listado dice USD 2,10 y la tabla arranca en 500 unidades, tu precio real a 100 unidades es otro. Pedilo por escrito.
2. Plazo de envío inflado. Dónde: el campo "Lead time" o "Processing time" de la ficha, y el mismo dato pedido por chat. Si el chat dice 7 días y la ficha dice 25, creele al número mayor.
3. Proveedor sin Trade Assurance. Dónde: el sello bajo el nombre de la empresa en la ficha. Sin ese sello no hay mediación posible si el pedido llega mal.
4. Pocos años en la plataforma. Dónde: la etiqueta de años junto al nombre del proveedor. Menos de 2 años sumado a un precio muy por debajo del mercado es la combinación clásica de cuenta desechable.
5. Sello "Verified Supplier" mal leído. Dónde: el badge de Alibaba. Significa que un auditor externo (SGS, TÜV Rheinland o Intertek) verificó licencia, instalaciones y capacidad. NO significa que probaron tu producto ni que sea fábrica: una comercializadora también puede tenerlo.
6. Sin licencia comercial verificable. Dónde: pedile el business license chino en PDF y compará el nombre legal con el que figura en la ficha de la plataforma. Si no coinciden, estás hablando con un intermediario que no te avisó que lo es.
7. Pago fuera de plataforma. Dónde: en el chat, cuando te piden Western Union, USDT o transferencia a una cuenta personal. Cualquier pago fuera del checkout de Alibaba pierde la cobertura de Trade Assurance. No hay excepción que valga la pena.
8. Muestra mal pedida. Dónde: en tu propio pedido de muestra. Pedí siempre tres cosas: la muestra en el empaque final de venta, foto o video del lote real en bodega, y el peso y las medidas de la caja máster. Sin eso no podés cotizar flete ni saber si lo que llega es lo que van a producir.
9. Fotos genéricas. Dónde: búsqueda inversa de imagen en Google. Si la misma foto aparece en decenas de fichas, el vendedor probablemente no tiene stock propio ni control de calidad.
10. Respuesta vaga sobre defectos. Dónde: preguntá directo por la tasa de defectos y la política de reposición. Si no te da un número y una regla, la reposición la vas a pagar vos.

TRES MOVIMIENTOS DE NEGOCIACIÓN (frase textual):
- Anclar con volumen futuro: "Estoy testeando con 100 unidades. Si funciona, el siguiente pedido es de 1.000. ¿Qué precio me das hoy pensando en ese segundo pedido?" En inglés simple para 1688 y Alibaba: "I am testing with 100 units. If it sells, my next order is 1,000. What price can you give me today based on that second order?"
- Partir el pago contra evidencia: "Pago 30% ahora y 70% contra foto del lote empacado y número de guía." En inglés: "I can pay 30% now and 70% after you send photos of the packed order and the tracking number."
- Pedir el desglose para negociar solo la parte cara: "Necesito el precio separado en producto, empaque y flete. Quiero comparar solo el producto." En inglés: "Please split the quote into product, packaging and shipping. I want to compare the product cost only."`
