// Knowledge base del agente broll-generator.
// Tipos de toma UGC, captura con iPhone y estructura temporal del ad vertical.
// Fuentes: skill interna ugc-creator (shot types, anclas de realismo, perfiles de cámara),
// Meta Ads Guide y Meta Advertising Standards de salud y bienestar, TikTok Ads Manager (consultados sep 2026).

export const UGC_SHOT_TYPES = `LOS 7 TIPOS DE TOMA UGC (encuadre, reglas de escena, duración):
1. REACCIÓN DE HOOK. Primer plano de cara, de mentón a frente, poco aire arriba. La persona reacciona A algo: sorpresa, fastidio, reconocimiento. Los ojos hacen el trabajo (ceja que sube, ojo que se abre), boca entreabierta o a mitad de palabra. Nada de sonrisa posada. 2 a 4 segundos.
2. PRODUCTO HÉROE. Macro o plano cerrado: el producto ocupa cerca del 60% del cuadro con las manos visibles. La etiqueta tiene que leerse y mirar a cámara. Un dedo señala o toca la característica de la que hablás. Foco en el producto, cara desenfocada atrás. 3 a 5 segundos.
3. DEMOSTRACIÓN DE USO. Plano medio con manos, cara y producto en el mismo cuadro. Mostrá el movimiento real (bombear, dosificar, aplicar, ajustar) y que se vea el cambio en la superficie o en la piel. Cerrá con la reacción de cómo se siente. 5 a 15 segundos.
4. TESTIMONIO A CÁMARA. Plano medio corto, de hombros a coronilla. Tiene que parecer que habla, no que lee: la mirada se va al costado un instante al pensar, el cuerpo se inclina apenas hacia adelante al afirmar, una mano gesticula. 8 a 30 segundos. Variantes: testimonio de mañana (sin maquillaje, luz temprana), post uso (piel enrojecida, producto al lado), comparación.
5. B ROLL DE ESTILO DE VIDA. Plano general o cuerpo entero. La persona NO mira a cámara. El producto aparece integrado en la escena, no exhibido. Que haya movimiento (caminar, estirar el brazo, sentarse) y que el entorno cuente algo. 3 a 8 segundos.
6. UNBOXING. Cenital o POV cerrado: manos, paquete y cara reaccionando en la parte alta del cuadro. Mostrá la mecánica real de abrir, el material de relleno y que el momento del reveal sea el clímax. 8 a 20 segundos.
7. ANTES Y DESPUÉS. El encuadre tiene que ser EXACTAMENTE el mismo en las dos tomas: mismo ángulo, misma luz, misma distancia. Solo cambia el estado. El "antes" tiene que ser más honesto que lo normal (textura de piel real, sin suavizado). El "después" muestra mejora natural, no transformación imposible. 3 segundos de antes, 3 de después y una placa de texto.

REGLA TRANSVERSAL: una toma, una idea. Si una toma necesita explicación para entenderse, partila en dos.
ORDEN DE RODAJE: grabá primero todas las tomas de un mismo encuadre y una misma luz, y recién ahí movés la cámara. Cambiar de set entre tomas es lo que rompe la continuidad.`

export const IPHONE_CAPTURE = `CAPTURA CON IPHONE: PERFILES DE CÁMARA Y ANCLAS DE REALISMO:
- Cámara frontal (selfie): equivalente 23 mm, f/2.2. Distorsiona: agranda el centro de la cara y la nariz. Balance de blancos más frío que la trasera. Suaviza la piel entre 15 y 20% aunque no uses modo retrato. Usala para testimonio, reacción y GRWM.
- Cámara trasera principal: equivalente 26 mm, f/1.78. Más nítida, color más cálido y fiel, bokeh óptico real. Usala para producto, b roll y exteriores. Para el producto héroe, el teleobjetivo de 77 mm (3x) comprime y hace ver mejor el envase.
- Selfie de espejo: teléfono visible a la altura del pecho, luz cenital de baño que tira sombra dura bajo la nariz, huellas y marcas de limpieza en el espejo. Sirve para prendas, fajas y cuerpo entero.
- Cenital: teléfono paralelo al piso a 90 grados, luz de ventana entrando por un solo lado, etiqueta legible, manos entrando desde abajo del cuadro. Sirve para unboxing y layouts de producto.
- POV a pulso: cámara a la altura del pecho mirando hacia abajo, sin estabilizar. El micro temblor de la mano es lo que lo hace creíble; no lo estabilices en edición.
- Luz: ventana al frente de la cara, nunca detrás. Grabá de día. Si la cara queda oscura, acercate a la ventana antes de tocar el brillo o los filtros.
- Audio: micrófono del teléfono a un metro o menos de la boca. Si el teléfono está más lejos, grabá con auriculares o repetí la toma más cerca. Ambiente cerrado, sin ventilador ni televisor de fondo.
- ANCLAS DE REALISMO. Si generás el material con IA van siempre en el prompt; si grabás real, no las corrijas en edición: poros visibles en nariz y frente, 2 o 3 pelos sueltos escapando del nacimiento del pelo, ojera natural con textura fina, tono de piel disparejo con rojez en nariz y mejillas, textura de tela con arrugas donde el cuerpo presiona, imperfecciones del entorno (polvo en la luz, objetos de fondo fuera de foco), luz despareja con un reventón leve en la punta de la nariz, aberración cromática y distorsión de borde propias del iPhone, uñas con cutícula y crecimiento visible, joyería que cae por gravedad y proyecta micro sombra.
- Prompt base para generador de imagen o video, en inglés y tal cual: "shot on iPhone front camera, 23mm equivalent, f/2.2, slight barrel distortion, natural window light from the left, visible skin pores on nose and forehead, 2-3 stray hairs at hairline, natural under-eye shadow, uneven skin tone with slight redness, fabric weave and real wrinkle physics, dust motes in window light, imperfect catchlight, chromatic aberration at high-contrast edges, hyper-realistic, not AI-smooth, not retouched, not stock photo".
- Negativos que van siempre: "no plastic skin, no AI-smooth perfection, no perfectly symmetrical face, no glossy mannequin texture, no HDR oversaturation, no studio lighting".
- Lo que NUNCA cambia entre tomas del mismo personaje: forma de la cara, tono de piel, color y forma de ojos, nariz, boca, mandíbula, lunares y cicatrices. Lo que sí puede cambiar: ropa, peinado, maquillaje, expresión y entorno.`

export const AD_TIMELINE = `ESTRUCTURA TEMPORAL, FORMATO Y ZONAS SEGURAS:
- Ad de 15 segundos: 0 a 3 hook (cara reaccionando o el problema en pantalla), 3 a 6 el problema dicho en primera persona, 6 a 9 producto en la mano con la etiqueta legible, 9 a 12 prueba o resultado, 12 a 15 CTA con oferta y forma de pago ("pagás cuando te llega").
- Ad de 30 segundos: 0 a 3 hook, 3 a 8 problema con una escena concreta, 8 a 13 cómo se usa, 13 a 20 resultado o testimonio, 20 a 26 objeción resuelta (talla, envío, devolución, contraentrega), 26 a 30 CTA con oferta.
- El CTA se dice y se escribe. El texto en pantalla tiene que funcionar sin audio.
- Relación de aspecto: 9:16 para Reels y Stories, resolución recomendada por Meta 1440 x 2560 px. Para el feed de Instagram, Meta recomienda 4:5 a 1440 x 1800 px (Meta Ads Guide, facebook.com/business/ads-guide, consultado sep 2026). Resolución mínima: 250 px de ancho para anuncios de menos de 30 segundos y 500 px de ancho para 30 segundos o más.
- Zonas seguras en Reels y Stories, dato oficial de Meta: dejar libre aproximadamente 14% arriba, 35% abajo y 6% a cada lado. Sobre un lienzo de 1080 x 1920 eso son unos 269 px arriba, 672 px abajo y 65 px a cada lado. Ni el texto ni el producto pueden caer ahí.
- TikTok no publica un número fijo de zona segura: dice que depende del formato, del largo del caption y de los elementos que agregues, y ofrece plantillas descargables. Dónde mirarlo: bajá la plantilla desde tu TikTok Ads Manager y montá el creativo encima (ads.tiktok.com/help, consultado sep 2026).
- Regla práctica que cubre las dos plataformas: componé todo lo importante dentro del tercio central vertical del cuadro. Ahí no llega la interfaz de nadie.
- Grabación: luz de ventana de frente, teléfono a la altura de los ojos, micrófono a un metro o menos de la boca.
- Duración: TikTok admite hasta 10 minutos en in feed y no publica una duración óptima. Meta tampoco publica una. La cifra de "21 a 34 segundos" que circula no tiene fuente oficial de TikTok. Decidí por retención medida en tu cuenta, no por la regla que escuchaste.
- Tomas de resultado que Meta acepta: para cosmética general, el antes y después está permitido pero el anuncio debe segmentarse a mayores de 18 años. Los anuncios de productos de pérdida o ganancia de peso también exigen segmentación 18+ y deben indicar con claridad el tiempo que toma ver resultados. Está prohibido cualquier texto que ataque la apariencia del espectador o que hable de inferioridad física (Meta Advertising Standards, salud y bienestar, transparency.meta.com/policies/ad-standards/restricted-goods-services/health-wellness, consultado sep 2026).
- Traducido a producción: mismo encuadre y misma luz en las dos tomas, resultado realista, plazo indicado en pantalla ("a las 3 semanas"), y ningún texto que ataque el cuerpo de quien mira. Si el resultado solo se ve cambiando el ángulo o la luz, no es un resultado: es un truco de cámara y Meta lo rechaza.
- Sonido: 88% de los usuarios de TikTok dice que el sonido es esencial en la experiencia (TikTok for Business, ads.tiktok.com/business/blog; TikTok atribuye ese dato a estudios distintos en notas distintas, así que tomalo como orden de magnitud). Grabá siempre con audio propio usable, aunque después le sumes música.`
