import {
  PenLine, FileText, MessageSquare, Zap,
  Activity, Type, Users,
  Target, Eye, Compass,
  ImageIcon, Film,
  Store, Truck, Package, FileEdit,
  LineChart, Calculator,
  Map, CheckSquare,
  type LucideIcon,
} from 'lucide-react'

export interface AgentDef {
  slug: string
  name: string
  description: string
  category: string
  icon: LucideIcon
  color: string
  requiredProviders: string[]
  defaultModel: string
  allowedModels: string[]
  isPremium: boolean
  outputFormat: 'markdown' | 'chat' | 'structured'
  inputSchema: Record<string, InputField>
}

export interface InputField {
  type: 'string'
  title: string
  description?: string
  enum?: string[]
  default?: string
  required?: boolean
}

const AGENTS: AgentDef[] = [
  // COPY
  { slug: 'content-engine', name: 'Content Engine', description: 'Genera ideas de contenido, hooks virales, scripts y captions optimizados para redes sociales.', category: 'copy', icon: PenLine, color: '#F59E0B', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o','gemini-2.5-pro'], isPremium: false, outputFormat: 'markdown', inputSchema: { niche: { type: 'string', title: 'Nicho', description: 'Tu nicho de negocio', required: true }, platform: { type: 'string', title: 'Plataforma', enum: ['Instagram Reels','TikTok','YouTube Shorts','Todas'], default: 'Instagram Reels', required: true }, objective: { type: 'string', title: 'Objetivo', enum: ['Awareness','Engagement','Ventas','Educación'], default: 'Engagement' }, tone: { type: 'string', title: 'Tono', enum: ['Profesional','Casual','Divertido','Urgente'], default: 'Casual' }, context: { type: 'string', title: 'Contexto adicional' } } },
  { slug: 'ugc-scripts', name: 'UGC Scripts', description: 'Genera guiones profesionales para contenido UGC con voz de marca auténtica.', category: 'copy', icon: FileText, color: '#F59E0B', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, audience: { type: 'string', title: 'Público objetivo', required: true }, duration: { type: 'string', title: 'Duración', enum: ['15 segundos','30 segundos','60 segundos'], default: '30 segundos' }, style: { type: 'string', title: 'Estilo', enum: ['Testimonial','Unboxing','Antes/Después','Tutorial','Storytelling'], default: 'Testimonial' }, benefits: { type: 'string', title: 'Beneficios clave', required: true } } },
  { slug: 'caption-generator', name: 'Caption Generator', description: 'Crea captions optimizados por plataforma con hashtags estratégicos y CTAs.', category: 'copy', icon: MessageSquare, color: '#F59E0B', requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-4o', allowedModels: ['claude-sonnet-4-20250514','gpt-4o','gemini-2.5-flash'], isPremium: false, outputFormat: 'markdown', inputSchema: { platform: { type: 'string', title: 'Plataforma', enum: ['Instagram','TikTok','Facebook','LinkedIn','Twitter/X'], default: 'Instagram', required: true }, topic: { type: 'string', title: 'Tema del post', required: true }, tone: { type: 'string', title: 'Tono', enum: ['Inspiracional','Educativo','Divertido','Promocional','Personal'], default: 'Educativo' }, cta: { type: 'string', title: 'CTA deseado' } } },
  { slug: 'hook-writer', name: 'Hook Writer', description: 'Genera ganchos virales para captar atención en los primeros 3 segundos.', category: 'copy', icon: Zap, color: '#F59E0B', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { topic: { type: 'string', title: 'Tema', required: true }, niche: { type: 'string', title: 'Nicho', required: true }, format: { type: 'string', title: 'Formato', enum: ['Video (spoken)','Texto (post)','Ambos'], default: 'Video (spoken)' } } },
  // ADS
  { slug: 'meta-doctor', name: 'Meta Doctor', description: 'Diagnostica tus campañas de Meta Ads (CPC, CTR, CPM, ROAS) con recomendaciones accionables.', category: 'ads', icon: Activity, color: '#EF4444', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { campaignData: { type: 'string', title: 'Datos de campaña', description: 'Pega métricas: nombre, spend, clicks, CTR, CPC, conversiones, ROAS', required: true }, budget: { type: 'string', title: 'Presupuesto diario' }, objective: { type: 'string', title: 'Objetivo', enum: ['Conversiones','Traffic','Engagement','Leads'], default: 'Conversiones', required: true }, offer: { type: 'string', title: 'Producto/Oferta' } } },
  { slug: 'ad-copy-generator', name: 'Ad Copy Generator', description: 'Genera textos de anuncios de alto rendimiento con variaciones A/B.', category: 'ads', icon: Type, color: '#EF4444', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, platform: { type: 'string', title: 'Plataforma', enum: ['Meta Ads','Google Ads','TikTok Ads'], default: 'Meta Ads', required: true }, audience: { type: 'string', title: 'Público objetivo', required: true }, offer: { type: 'string', title: 'Oferta/Promoción' }, tone: { type: 'string', title: 'Tono', enum: ['Urgente','Aspiracional','Educativo','FOMO'], default: 'Urgente' } } },
  { slug: 'audience-analyzer', name: 'Audience Analyzer', description: 'Analiza y define tu público objetivo ideal con buyer personas detallados.', category: 'ads', icon: Users, color: '#EF4444', requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-4o', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto/Servicio', required: true }, industry: { type: 'string', title: 'Industria', required: true }, region: { type: 'string', title: 'País/Región', default: 'LATAM' }, price: { type: 'string', title: 'Rango de precio' } } },
  // RESEARCH
  { slug: 'product-hunter', name: 'Product Hunter', description: 'Valida productos con scoring de 12 criterios. Encuentra ganadores.', category: 'research', icon: Target, color: '#3B82F6', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'structured', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, source: { type: 'string', title: 'Proveedor/Fuente' }, cost: { type: 'string', title: 'Precio de costo', required: true }, price: { type: 'string', title: 'Precio de venta estimado', required: true }, niche: { type: 'string', title: 'Nicho' } } },
  { slug: 'competitor-watch', name: 'Competitor Watch', description: 'Analiza competidores: oferta, precios, ads y oportunidades de diferenciación.', category: 'research', icon: Eye, color: '#3B82F6', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { competitor: { type: 'string', title: 'Nombre del competidor', required: true }, url: { type: 'string', title: 'URL de la tienda/perfil' }, yourProduct: { type: 'string', title: 'Tu producto/nicho', required: true }, focus: { type: 'string', title: 'Enfoque', enum: ['Análisis completo','Solo precios','Solo ads/creativos','Solo propuesta de valor'], default: 'Análisis completo' } } },
  { slug: 'niche-analyzer', name: 'Niche Analyzer', description: 'Evalúa nichos con datos de demanda, competencia y rentabilidad.', category: 'research', icon: Compass, color: '#3B82F6', requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-4o', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { niche: { type: 'string', title: 'Nicho a analizar', required: true }, region: { type: 'string', title: 'Región', enum: ['LATAM','Colombia','México','Global'], default: 'LATAM' }, model: { type: 'string', title: 'Modelo de negocio', enum: ['Dropshipping','Marca propia','Print on demand','Digital products'], default: 'Dropshipping' } } },
  // UGC
  { slug: 'image-prompts', name: 'Image Prompts', description: 'Genera prompts optimizados para crear imágenes con IA de productos y lifestyle.', category: 'ugc', icon: ImageIcon, color: '#EC4899', requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-4o', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { subject: { type: 'string', title: 'Producto/Escena', required: true }, style: { type: 'string', title: 'Estilo visual', enum: ['Fotografía de producto','Lifestyle','Flat lay','Minimalista','Editorial','UGC realista'], default: 'Fotografía de producto', required: true }, usage: { type: 'string', title: 'Uso', enum: ['Anuncios','Redes sociales','Tienda online','Email marketing'], default: 'Anuncios' }, model: { type: 'string', title: 'Modelo de IA', enum: ['Midjourney','DALL-E 3','Flux','Ideogram','General'], default: 'General' } } },
  { slug: 'broll-generator', name: 'B-Roll Generator', description: 'Planifica shot lists profesionales para producción de B-Roll.', category: 'ugc', icon: Film, color: '#EC4899', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: true, outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, videoType: { type: 'string', title: 'Tipo de video', enum: ['Unboxing','Tutorial','Testimonial','Lifestyle','Antes/Después'], default: 'Lifestyle', required: true }, shots: { type: 'string', title: 'Número de tomas', enum: ['5','8','10','15'], default: '8' }, style: { type: 'string', title: 'Estilo visual', enum: ['Limpio/Minimalista','Cálido/Orgánico','Energético/Dinámico','Lujoso/Premium'], default: 'Limpio/Minimalista' } } },
  // ECOMMERCE
  { slug: 'shopify-assistant', name: 'Shopify Assistant', description: 'Tu asistente experto en Shopify: optimización, descripciones, SEO y conversión.', category: 'ecommerce', icon: Store, color: '#22C55E', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'chat', inputSchema: { question: { type: 'string', title: 'Tu pregunta', required: true } } },
  { slug: 'logistics-tracker', name: 'Logistics Tracker', description: 'Analiza tu logística, detecta cuellos de botella y recomienda optimizaciones.', category: 'ecommerce', icon: Truck, color: '#22C55E', requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-4o', allowedModels: ['gpt-4o','claude-sonnet-4-20250514'], isPremium: false, outputFormat: 'markdown', inputSchema: { logisticsData: { type: 'string', title: 'Datos de logística', required: true }, country: { type: 'string', title: 'País', enum: ['Colombia','México','Chile','Argentina','Otro'], default: 'Colombia', required: true }, mainIssue: { type: 'string', title: 'Problema principal', enum: ['Tiempos de entrega','Costos altos','Devoluciones','Tracking','General'], default: 'General' } } },
  { slug: 'supplier-finder', name: 'Supplier Finder', description: 'Encuentra y evalúa proveedores de dropshipping con comparativas detalladas.', category: 'ecommerce', icon: Package, color: '#22C55E', requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-4o', allowedModels: ['gpt-4o','claude-sonnet-4-20250514'], isPremium: false, outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto a sourcear', required: true }, platform: { type: 'string', title: 'Plataforma preferida', enum: ['Dropi','AliExpress','CJ Dropshipping','1688','Sin preferencia'], default: 'Sin preferencia' }, volume: { type: 'string', title: 'Volumen mensual', enum: ['1-50 unidades','50-200','200-500','500+'], default: '50-200' }, destination: { type: 'string', title: 'País destino', enum: ['Colombia','México','Chile','Argentina','Otro'], default: 'Colombia', required: true } } },
  { slug: 'product-descriptions', name: 'Product Descriptions', description: 'Genera descripciones SEO-optimizadas con storytelling que convierten.', category: 'ecommerce', icon: FileEdit, color: '#22C55E', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: false, outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Nombre del producto', required: true }, category: { type: 'string', title: 'Categoría', required: true }, price: { type: 'string', title: 'Precio de venta' }, benefits: { type: 'string', title: 'Beneficios principales', required: true }, keywords: { type: 'string', title: 'Keywords SEO (opcional)' } } },
  // ANALYTICS
  { slug: 'performance-tracker', name: 'Performance Tracker', description: 'Analiza métricas de tu negocio y genera insights accionables.', category: 'analytics', icon: LineChart, color: '#8B5CF6', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: true, outputFormat: 'markdown', inputSchema: { metrics: { type: 'string', title: 'Métricas', description: 'Pega tus métricas de negocio', required: true }, period: { type: 'string', title: 'Período', enum: ['Última semana','Último mes','Últimos 3 meses','YTD'], default: 'Último mes' }, question: { type: 'string', title: 'Pregunta específica (opcional)' } } },
  { slug: 'roi-calculator', name: 'ROI Calculator', description: 'Calcula ROI con análisis detallado de unit economics.', category: 'analytics', icon: Calculator, color: '#8B5CF6', requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-4o', allowedModels: ['gpt-4o','claude-sonnet-4-20250514'], isPremium: false, outputFormat: 'structured', inputSchema: { cost: { type: 'string', title: 'Costo del producto', required: true }, price: { type: 'string', title: 'Precio de venta', required: true }, shipping: { type: 'string', title: 'Costo de envío' }, adSpend: { type: 'string', title: 'Gasto en ads' }, other: { type: 'string', title: 'Otros costos (opcional)' } } },
  // STRATEGY
  { slug: 'business-planner', name: 'Business Planner', description: 'Crea planes de negocio ecommerce con análisis, proyecciones y roadmap.', category: 'strategy', icon: Map, color: '#F97316', requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-4-20250514', allowedModels: ['claude-sonnet-4-20250514','gpt-4o'], isPremium: true, outputFormat: 'markdown', inputSchema: { idea: { type: 'string', title: 'Idea de negocio', required: true }, budget: { type: 'string', title: 'Presupuesto inicial', required: true }, experience: { type: 'string', title: 'Experiencia', enum: ['Completo principiante','Algo de experiencia','Intermedio','Avanzado'], default: 'Algo de experiencia' }, time: { type: 'string', title: 'Tiempo disponible', enum: ['Part-time (2-4h/día)','Full-time','Solo fines de semana'], default: 'Part-time (2-4h/día)' } } },
  { slug: 'launch-checklist', name: 'Launch Checklist', description: 'Genera un checklist pre-lanzamiento con prioridades y deadlines.', category: 'strategy', icon: CheckSquare, color: '#F97316', requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-4o', allowedModels: ['gpt-4o','claude-sonnet-4-20250514'], isPremium: false, outputFormat: 'markdown', inputSchema: { type: { type: 'string', title: 'Tipo de lanzamiento', enum: ['Nueva tienda','Nuevo producto','Relanzamiento','Nueva categoría'], default: 'Nueva tienda', required: true }, platform: { type: 'string', title: 'Plataforma', enum: ['Shopify','WooCommerce','TiendaNube','Otra'], default: 'Shopify', required: true }, date: { type: 'string', title: 'Fecha objetivo' }, ready: { type: 'string', title: 'Qué tienes listo' } } },
]

export function getAgent(slug: string): AgentDef | undefined {
  return AGENTS.find((a) => a.slug === slug)
}

export function getAgentsByCategory(category?: string): AgentDef[] {
  if (!category) return AGENTS
  return AGENTS.filter((a) => a.category === category)
}

export function getAllAgents(): AgentDef[] {
  return AGENTS
}
