import {
  PenLine, FileText, MessageSquare, Zap,
  Activity, Type, Users,
  Target, Eye, Compass,
  ImageIcon, Film,
  Store, Truck, Package, FileEdit,
  LineChart, Calculator,
  Map, CheckSquare,
  Palette, ClipboardCheck, Sparkles, Code2, Layout, Network, ScanSearch, Rocket,
  type LucideIcon,
} from 'lucide-react'

export interface AgentDef {
  slug: string
  name: string
  description: string
  category: string
  icon: LucideIcon
  requiredProviders: string[]
  defaultModel: string
  allowedModels: string[]
  modelTier: 'economy' | 'standard' | 'premium'
  outputFormat: 'markdown' | 'chat' | 'structured'
  inputSchema: Record<string, InputField>
}

export interface InputField {
  type: 'string'
  title: string
  description?: string
  enum?: string[]
  default?: string
  required?: boolean
}

const AGENTS: AgentDef[] = [
  // COPY (4)
  { slug: 'content-engine', name: 'Content Engine', description: 'Genera ideas de contenido, hooks virales, scripts y captions optimizados para redes sociales.', category: 'copy', icon: PenLine, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { niche: { type: 'string', title: 'Nicho', description: 'Tu nicho de negocio', required: true }, platform: { type: 'string', title: 'Plataforma', enum: ['Instagram Reels','TikTok','YouTube Shorts','Todas'], default: 'Instagram Reels', required: true }, objective: { type: 'string', title: 'Objetivo', enum: ['Awareness','Engagement','Ventas','Educación'], default: 'Engagement' }, tone: { type: 'string', title: 'Tono', enum: ['Profesional','Casual','Divertido','Urgente'], default: 'Casual' }, context: { type: 'string', title: 'Contexto adicional' } } },
  { slug: 'ugc-scripts', name: 'UGC Scripts', description: 'Genera guiones profesionales para contenido UGC con voz de marca auténtica.', category: 'copy', icon: FileText, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-haiku-4-5', allowedModels: ['claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash','claude-sonnet-5','gpt-5.6-terra'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, audience: { type: 'string', title: 'Público objetivo', required: true }, duration: { type: 'string', title: 'Duración', enum: ['15 segundos','30 segundos','60 segundos'], default: '30 segundos' }, style: { type: 'string', title: 'Estilo', enum: ['Testimonial','Unboxing','Antes/Después','Tutorial','Storytelling'], default: 'Testimonial' }, benefits: { type: 'string', title: 'Beneficios clave', required: true } } },
  { slug: 'caption-generator', name: 'Caption Generator', description: 'Crea captions optimizados por plataforma con hashtags estratégicos y CTAs.', category: 'copy', icon: MessageSquare, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-luna', allowedModels: ['gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash','gpt-5.6-terra','claude-sonnet-5'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { platform: { type: 'string', title: 'Plataforma', enum: ['Instagram','TikTok','Facebook','LinkedIn','Twitter/X'], default: 'Instagram', required: true }, topic: { type: 'string', title: 'Tema del post', required: true }, tone: { type: 'string', title: 'Tono', enum: ['Inspiracional','Educativo','Divertido','Promocional','Personal'], default: 'Educativo' }, cta: { type: 'string', title: 'CTA deseado' } } },
  { slug: 'hook-writer', name: 'Hook Writer', description: 'Genera ganchos virales para captar atención en los primeros 3 segundos.', category: 'copy', icon: Zap, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-haiku-4-5', allowedModels: ['claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash','claude-sonnet-5','gpt-5.6-terra'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { topic: { type: 'string', title: 'Tema', required: true }, niche: { type: 'string', title: 'Nicho', required: true }, format: { type: 'string', title: 'Formato', enum: ['Video (spoken)','Texto (post)','Ambos'], default: 'Video (spoken)' } } },
  // ADS (5)
  { slug: 'meta-doctor', name: 'Meta Doctor', description: 'Diagnostica tus campañas de Meta Ads (CPC, CTR, CPM, ROAS) con recomendaciones accionables.', category: 'ads', icon: Activity, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { campaignData: { type: 'string', title: 'Datos de campaña', description: 'Pega métricas: nombre, spend, clicks, CTR, CPC, conversiones, ROAS', required: true }, budget: { type: 'string', title: 'Presupuesto diario' }, objective: { type: 'string', title: 'Objetivo', enum: ['Conversiones','Traffic','Engagement','Leads'], default: 'Conversiones', required: true }, offer: { type: 'string', title: 'Producto/Oferta' }, vertical: { type: 'string', title: 'Vertical', enum: ['Ecommerce','Belleza','Moda','Tech','Suplementos','Otro'], default: 'Ecommerce' }, country: { type: 'string', title: 'País', enum: ['Colombia','México','Chile','Argentina','USA','Otro'], default: 'Colombia' } } },
  { slug: 'ad-copy-generator', name: 'Ad Copy Generator', description: 'Genera textos de anuncios de alto rendimiento con variaciones A/B.', category: 'ads', icon: Type, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, platform: { type: 'string', title: 'Plataforma', enum: ['Meta Ads','Google Ads','TikTok Ads'], default: 'Meta Ads', required: true }, audience: { type: 'string', title: 'Público objetivo', required: true }, offer: { type: 'string', title: 'Oferta/Promoción' }, tone: { type: 'string', title: 'Tono', enum: ['Urgente','Aspiracional','Educativo','FOMO'], default: 'Urgente' }, framework: { type: 'string', title: 'Framework', enum: ['AIDA','PAS','BAB','4P','FAB','Star-Story-Solution','Auto (mejor para el caso)'], default: 'Auto (mejor para el caso)' }, adFormat: { type: 'string', title: 'Formato del ad', enum: ['Feed cuadrado 1080x1080','Story 1080x1920','Banner 1200x628','Todos'], default: 'Feed cuadrado 1080x1080' } } },
  { slug: 'audience-analyzer', name: 'Audience Analyzer', description: 'Analiza y define tu público objetivo ideal con buyer personas detallados.', category: 'ads', icon: Users, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-terra', allowedModels: ['gpt-5.6-terra','gemini-2.5-pro','claude-sonnet-5','gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto/Servicio', required: true }, industry: { type: 'string', title: 'Industria', required: true }, region: { type: 'string', title: 'País/Región', default: 'LATAM' }, price: { type: 'string', title: 'Rango de precio' } } },
  { slug: 'ad-creative-planner', name: 'Ad Creative Planner', description: 'Genera briefs creativos completos con layout, copy por bloque y prompts de imagen.', category: 'ads', icon: Palette, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto/URL', required: true }, platform: { type: 'string', title: 'Plataforma', enum: ['Meta Ads','Google Display','TikTok','Todas'], default: 'Meta Ads', required: true }, objective: { type: 'string', title: 'Objetivo', enum: ['Conversiones','Awareness','Retargeting','Lanzamiento'], default: 'Conversiones' }, adFormat: { type: 'string', title: 'Formato', enum: ['Feed cuadrado 1080x1080','Feed vertical 1080x1350','Story/Reel 1080x1920','Todos'], default: 'Feed cuadrado 1080x1080' }, brandColors: { type: 'string', title: 'Colores de marca (hex)' }, references: { type: 'string', title: 'Referencias/Estilo' }, variants: { type: 'string', title: 'Variantes', enum: ['3','5','8'], default: '3' } } },
  { slug: 'ads-auditor', name: 'Ads Auditor', description: 'Auditoría profunda de campañas con scoring 250+ checks y grading A-F.', category: 'ads', icon: ClipboardCheck, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','claude-opus-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna'], modelTier: 'premium', outputFormat: 'structured', inputSchema: { platform: { type: 'string', title: 'Plataforma', enum: ['Meta Ads','Google Ads','TikTok Ads','Multi-plataforma'], default: 'Meta Ads', required: true }, campaignData: { type: 'string', title: 'Datos de campaña', description: 'Pega estructura, métricas, audiencias, presupuesto, creativos', required: true }, budget: { type: 'string', title: 'Presupuesto mensual total', required: true }, vertical: { type: 'string', title: 'Vertical', enum: ['Ecommerce','Lead Gen','SaaS','App Install','Otro'], default: 'Ecommerce' }, country: { type: 'string', title: 'País', enum: ['Colombia','México','Chile','Argentina','USA','Otro'], default: 'Colombia' } } },
  // RESEARCH (3)
  { slug: 'product-hunter', name: 'Product Hunter', description: 'Valida productos con scoring de 12 criterios. Encuentra ganadores.', category: 'research', icon: Target, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','claude-opus-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna'], modelTier: 'premium', outputFormat: 'structured', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, source: { type: 'string', title: 'Proveedor/Fuente' }, cost: { type: 'string', title: 'Precio de costo', required: true }, price: { type: 'string', title: 'Precio de venta estimado', required: true }, niche: { type: 'string', title: 'Nicho' } } },
  { slug: 'competitor-watch', name: 'Competitor Watch', description: 'Analiza competidores: oferta, precios, ads y oportunidades de diferenciación.', category: 'research', icon: Eye, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { competitor: { type: 'string', title: 'Nombre del competidor', required: true }, url: { type: 'string', title: 'URL de la tienda/perfil' }, yourProduct: { type: 'string', title: 'Tu producto/nicho', required: true }, focus: { type: 'string', title: 'Enfoque', enum: ['Análisis completo','Solo precios','Solo ads/creativos','Solo propuesta de valor'], default: 'Análisis completo' } } },
  { slug: 'niche-analyzer', name: 'Niche Analyzer', description: 'Evalúa nichos con datos de demanda, competencia y rentabilidad.', category: 'research', icon: Compass, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-terra', allowedModels: ['gpt-5.6-terra','gemini-2.5-pro','claude-sonnet-5','gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { niche: { type: 'string', title: 'Nicho a analizar', required: true }, region: { type: 'string', title: 'Región', enum: ['LATAM','Colombia','México','Global'], default: 'LATAM' }, model: { type: 'string', title: 'Modelo de negocio', enum: ['Dropshipping','Marca propia','Print on demand','Digital products'], default: 'Dropshipping' } } },
  // UGC (3)
  { slug: 'image-prompts', name: 'Image Prompts', description: 'Genera prompts optimizados para crear imágenes con IA de productos y lifestyle.', category: 'ugc', icon: ImageIcon, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-luna', allowedModels: ['gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash','gpt-5.6-terra','claude-sonnet-5'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { subject: { type: 'string', title: 'Producto/Escena', required: true }, style: { type: 'string', title: 'Estilo visual', enum: ['Fotografía de producto','Lifestyle','Flat lay','Minimalista','Editorial','UGC realista'], default: 'Fotografía de producto', required: true }, usage: { type: 'string', title: 'Uso', enum: ['Anuncios','Redes sociales','Tienda online','Email marketing'], default: 'Anuncios' }, model: { type: 'string', title: 'Modelo de IA', enum: ['Midjourney','DALL-E 3','Flux','Ideogram','General'], default: 'General' } } },
  { slug: 'broll-generator', name: 'B-Roll Generator', description: 'Planifica shot lists profesionales para producción de B-Roll.', category: 'ugc', icon: Film, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-haiku-4-5', allowedModels: ['claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash','claude-sonnet-5','gpt-5.6-terra'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, videoType: { type: 'string', title: 'Tipo de video', enum: ['Unboxing','Tutorial','Testimonial','Lifestyle','Antes/Después'], default: 'Lifestyle', required: true }, shots: { type: 'string', title: 'Número de tomas', enum: ['5','8','10','15'], default: '8' }, style: { type: 'string', title: 'Estilo visual', enum: ['Limpio/Minimalista','Cálido/Orgánico','Energético/Dinámico','Lujoso/Premium'], default: 'Limpio/Minimalista' } } },
  { slug: 'ad-image-prompter', name: 'Ad Image Prompter', description: 'Genera prompts profesionales de imagen para creativos publicitarios.', category: 'ugc', icon: Sparkles, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-luna', allowedModels: ['gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash','gpt-5.6-terra','claude-sonnet-5'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto', required: true }, adType: { type: 'string', title: 'Tipo de anuncio', enum: ['Feed estático','Story/Reel fondo','Carousel card','Banner display','UGC lifestyle'], default: 'Feed estático', required: true }, composition: { type: 'string', title: 'Composición', enum: ['Producto centrado','Split horizontal','Producto hero con overlay','Grid de beneficios','Solo fondo'], default: 'Producto centrado' }, brandColors: { type: 'string', title: 'Paleta de marca (hex)' }, mood: { type: 'string', title: 'Mood', enum: ['Premium/Lujoso','Natural/Orgánico','Energético/Dinámico','Minimalista/Clean','Cálido/Confortable'], default: 'Minimalista/Clean' }, model: { type: 'string', title: 'Modelo de IA', enum: ['Midjourney','DALL-E 3','Flux','Ideogram','General'], default: 'General' } } },
  // ECOMMERCE (6)
  { slug: 'shopify-assistant', name: 'Shopify Assistant', description: 'Tu asistente experto en Shopify: optimización, descripciones, SEO y conversión.', category: 'ecommerce', icon: Store, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna'], modelTier: 'standard', outputFormat: 'chat', inputSchema: { question: { type: 'string', title: 'Tu pregunta', required: true } } },
  { slug: 'logistics-tracker', name: 'Logistics Tracker', description: 'Analiza tu logística, detecta cuellos de botella y recomienda optimizaciones.', category: 'ecommerce', icon: Truck, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-luna', allowedModels: ['gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash','gpt-5.6-terra','claude-sonnet-5'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { logisticsData: { type: 'string', title: 'Datos de logística', required: true }, country: { type: 'string', title: 'País', enum: ['Colombia','México','Chile','Argentina','Otro'], default: 'Colombia', required: true }, mainIssue: { type: 'string', title: 'Problema principal', enum: ['Tiempos de entrega','Costos altos','Devoluciones','Tracking','General'], default: 'General' } } },
  { slug: 'supplier-finder', name: 'Supplier Finder', description: 'Encuentra y evalúa proveedores de dropshipping con comparativas detalladas.', category: 'ecommerce', icon: Package, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-luna', allowedModels: ['gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash','gpt-5.6-terra','claude-sonnet-5'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Producto a sourcear', required: true }, platform: { type: 'string', title: 'Plataforma preferida', enum: ['Dropi','AliExpress','CJ Dropshipping','1688','Sin preferencia'], default: 'Sin preferencia' }, volume: { type: 'string', title: 'Volumen mensual', enum: ['1-50 unidades','50-200','200-500','500+'], default: '50-200' }, destination: { type: 'string', title: 'País destino', enum: ['Colombia','México','Chile','Argentina','Otro'], default: 'Colombia', required: true } } },
  { slug: 'product-descriptions', name: 'Product Descriptions', description: 'Genera descripciones SEO-optimizadas con storytelling que convierten.', category: 'ecommerce', icon: FileEdit, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-haiku-4-5', allowedModels: ['claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash','claude-sonnet-5','gpt-5.6-terra'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { product: { type: 'string', title: 'Nombre del producto', required: true }, category: { type: 'string', title: 'Categoría', required: true }, price: { type: 'string', title: 'Precio de venta' }, benefits: { type: 'string', title: 'Beneficios principales', required: true }, keywords: { type: 'string', title: 'Keywords SEO (opcional)' } } },
  { slug: 'shopify-section-builder', name: 'Shopify Section Builder', description: 'Genera secciones Shopify Liquid completas y listas para producción.', category: 'ecommerce', icon: Code2, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','claude-opus-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna'], modelTier: 'premium', outputFormat: 'markdown', inputSchema: { sectionType: { type: 'string', title: 'Tipo de sección', enum: ['Hero Banner','Carousel de productos','Trust badges','FAQ Accordion','Testimonios','Beneficios/Features','Tabla comparativa','Banner CTA','Grid de colecciones','Newsletter signup','Marquee/Ticker','Personalizado'], default: 'Hero Banner', required: true }, description: { type: 'string', title: 'Descripción', description: 'Describe qué debe hacer y cómo debe verse', required: true }, approach: { type: 'string', title: 'Enfoque', enum: ['Liquid puro (sin JS)','Liquid + Vanilla JS','Con interactividad avanzada'], default: 'Liquid puro (sin JS)', required: true }, style: { type: 'string', title: 'Estilo visual', enum: ['Minimalista','Moderno/Bold','Orgánico/Natural','Premium/Lujoso','Ecommerce estándar'], default: 'Minimalista' }, responsive: { type: 'string', title: 'Responsive', enum: ['Mobile-first','Desktop-first'], default: 'Mobile-first' }, colorScheme: { type: 'string', title: 'Colores (opcional)' } } },
  { slug: 'landing-page-builder', name: 'Landing Page Builder', description: 'Diseña la estructura completa de landing pages Shopify optimizadas para conversión.', category: 'ecommerce', icon: Layout, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { goal: { type: 'string', title: 'Objetivo', enum: ['Lanzamiento de producto','Oferta/Promoción','Lead magnet','Pre-lanzamiento','Colección especial'], required: true }, product: { type: 'string', title: 'Producto principal', required: true }, audience: { type: 'string', title: 'Público objetivo', required: true }, trust: { type: 'string', title: 'Elementos de confianza', description: 'Reviews, garantías, WhatsApp, certificaciones' }, country: { type: 'string', title: 'País', enum: ['Colombia','México','Chile','Argentina','Otro'], default: 'Colombia' } } },
  // ANALYTICS (2)
  { slug: 'performance-tracker', name: 'Performance Tracker', description: 'Analiza métricas de tu negocio y genera insights accionables.', category: 'analytics', icon: LineChart, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','claude-opus-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna'], modelTier: 'premium', outputFormat: 'markdown', inputSchema: { metrics: { type: 'string', title: 'Métricas', description: 'Pega tus métricas de negocio', required: true }, period: { type: 'string', title: 'Período', enum: ['Última semana','Último mes','Últimos 3 meses','YTD'], default: 'Último mes' }, question: { type: 'string', title: 'Pregunta específica (opcional)' }, platform: { type: 'string', title: 'Plataforma', enum: ['Meta Ads','Google Ads','TikTok','Multi-plataforma','Tienda/General'], default: 'Tienda/General' }, vertical: { type: 'string', title: 'Vertical', enum: ['Ecommerce','Belleza','Moda','Tech','Suplementos','Otro'], default: 'Ecommerce' } } },
  { slug: 'roi-calculator', name: 'ROI Calculator', description: 'Calcula ROI con análisis detallado de unit economics.', category: 'analytics', icon: Calculator, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-luna', allowedModels: ['gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash','gpt-5.6-terra','claude-sonnet-5'], modelTier: 'economy', outputFormat: 'structured', inputSchema: { cost: { type: 'string', title: 'Costo del producto', required: true }, price: { type: 'string', title: 'Precio de venta', required: true }, shipping: { type: 'string', title: 'Costo de envío' }, adSpend: { type: 'string', title: 'Gasto en ads' }, other: { type: 'string', title: 'Otros costos (opcional)' } } },
  // STRATEGY (3)
  { slug: 'business-planner', name: 'Business Planner', description: 'Crea planes de negocio ecommerce con análisis, proyecciones y roadmap.', category: 'strategy', icon: Map, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','claude-opus-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna'], modelTier: 'premium', outputFormat: 'markdown', inputSchema: { idea: { type: 'string', title: 'Idea de negocio', required: true }, budget: { type: 'string', title: 'Presupuesto inicial', required: true }, experience: { type: 'string', title: 'Experiencia', enum: ['Completo principiante','Algo de experiencia','Intermedio','Avanzado'], default: 'Algo de experiencia' }, time: { type: 'string', title: 'Tiempo disponible', enum: ['Part-time (2-4h/día)','Full-time','Solo fines de semana'], default: 'Part-time (2-4h/día)' } } },
  { slug: 'launch-checklist', name: 'Launch Checklist', description: 'Genera un checklist pre-lanzamiento con prioridades y deadlines.', category: 'strategy', icon: CheckSquare, requiredProviders: ['anthropic','openai','google'], defaultModel: 'gpt-5.6-luna', allowedModels: ['gpt-5.6-luna','claude-haiku-4-5','gemini-2.5-flash','gpt-5.6-terra','claude-sonnet-5'], modelTier: 'economy', outputFormat: 'markdown', inputSchema: { type: { type: 'string', title: 'Tipo de lanzamiento', enum: ['Nueva tienda','Nuevo producto','Relanzamiento','Nueva categoría'], default: 'Nueva tienda', required: true }, platform: { type: 'string', title: 'Plataforma', enum: ['Shopify','WooCommerce','TiendaNube','Otra'], default: 'Shopify', required: true }, date: { type: 'string', title: 'Fecha objetivo' }, ready: { type: 'string', title: 'Qué tienes listo' } } },
  { slug: 'campaign-architect', name: 'Campaign Architect', description: 'Diseña arquitecturas de campañas multi-plataforma con budget allocation.', category: 'strategy', icon: Network, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','claude-opus-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna'], modelTier: 'premium', outputFormat: 'markdown', inputSchema: { objective: { type: 'string', title: 'Objetivo', enum: ['Lanzamiento (0 a 1)','Escalar (ya vende)','Diversificar plataformas','Black Friday/Cyber','Reactivar ROAS bajo'], required: true }, budget: { type: 'string', title: 'Presupuesto mensual (USD)', required: true }, product: { type: 'string', title: 'Producto/Tienda', required: true }, currentPlatforms: { type: 'string', title: 'Plataformas actuales', enum: ['Solo Meta','Meta + Google','Meta + Google + TikTok','Ninguna (empezando)'], default: 'Solo Meta' }, country: { type: 'string', title: 'País principal', enum: ['Colombia','México','Chile','Argentina','USA','Multi-LATAM'], default: 'Colombia' }, aov: { type: 'string', title: 'Ticket promedio (AOV)' } } },
  // CRO (2)
  { slug: 'cro-auditor', name: 'CRO Auditor', description: 'Auditoría de conversión con framework de 10 puntos y priorización por impacto.', category: 'cro', icon: ScanSearch, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','claude-opus-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna'], modelTier: 'premium', outputFormat: 'structured', inputSchema: { storeUrl: { type: 'string', title: 'URL de la tienda', required: true }, pageType: { type: 'string', title: 'Tipo de página', enum: ['Homepage','PDP (Producto)','Colección','Landing page','Checkout flow','Tienda completa'], default: 'PDP (Producto)', required: true }, currentCR: { type: 'string', title: 'Conversion rate actual', description: 'Ej: 1.8%' }, issues: { type: 'string', title: 'Problemas observados' }, country: { type: 'string', title: 'País', enum: ['Colombia','México','Chile','Argentina','Otro'], default: 'Colombia' } } },
  { slug: 'landing-optimizer', name: 'Landing Optimizer', description: 'Optimiza landing pages para conversión con trust signals LATAM.', category: 'cro', icon: Rocket, requiredProviders: ['anthropic','openai','google'], defaultModel: 'claude-sonnet-5', allowedModels: ['claude-sonnet-5','gpt-5.6-terra','gemini-2.5-pro','claude-haiku-4-5','gpt-5.6-luna','gemini-2.5-flash'], modelTier: 'standard', outputFormat: 'markdown', inputSchema: { currentStructure: { type: 'string', title: 'Estructura actual', description: 'Describe las secciones de tu landing page', required: true }, product: { type: 'string', title: 'Producto', required: true }, traffic: { type: 'string', title: 'Fuente de tráfico', enum: ['Meta Ads','Google Ads','TikTok','Orgánico','WhatsApp','Mixto'], default: 'Meta Ads' }, paymentMethods: { type: 'string', title: 'Métodos de pago' }, country: { type: 'string', title: 'País', enum: ['Colombia','México','Chile','Argentina','Otro'], default: 'Colombia' } } },
]

export function getAgent(slug: string): AgentDef | undefined {
  return AGENTS.find((a) => a.slug === slug)
}

export function getAgentsByCategory(category?: string): AgentDef[] {
  if (!category) return AGENTS
  return AGENTS.filter((a) => a.category === category)
}

export function getAllAgents(): AgentDef[] {
  return AGENTS
}
